import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderPage from "./header/page";
import FooterPage from "./footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <HeaderPage/>
        {children}
        <FooterPage/>
      </body>
    </html>
  );
}
